### ISSUE TITLE
6.72 jb 2 K.P

### ISSUE THREAD

**Issue by homer243** [sleirsgoevy/ps4jb2#9]
the exploit runs very fast all time success but whenever you exit the browser or go to settings
it K.P

**Comment by viggen66** [comment]
This new 6.72 jb 2 is a huge milestone from sleirsgoevy, since it never fails to successfully exploit the kernel, but as homer243 said, when exiting browser, game library or settings sometimes results in k.p, wondering if spraying more cores, can result in better stability after exploit.

**Comment by sleirsgoevy** [comment]
If anybody wants to get updates for this, please ping in Discord, 'coz I no longer have a 6.72 PS4 and will need testers to develop it.

**Comment by viggen66** [comment]
sleirsgoevy, I can help you, you are very close of a perfect kernel exploit.

**Comment by viggen66** [comment]
Regarding test users, besides me, it is my belief that on twitter, lots of users are willing to help, moreover once I asked  Chendochap, since the USB stick bug is present on firmware ranging 1.0 to 9.0, if he would port the exploit to lower firmware, the response " is not that difficult to port if you want to do it yourself, it's mainly finding gadgets to get that kernel rop chain going.", unfortunately, I'm not a software engineer, need to enroll in a CS degree.

**Comment by homer243** [comment]
> If anybody wants to get updates for this, please ping in Discord, 'coz I no longer have a 6.72 PS4 and will need testers to develop it.

sure i have 6.72 slim am ready to help you test
